# Generated by Django 5.2.3 on 2025-06-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formations",
            options={
                "ordering": ["team", "tournament", "tactic_name"],
                "verbose_name": "Formazione",
                "verbose_name_plural": "Formazioni",
            },
        ),
    ]
