# Generated by Django 5.2.3 on 2025-07-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_formations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, help_text='Data di fine del torneo', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se il torneo è attivo'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del torneo', null=True, upload_to='tournaments/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, help_text='Data di inizio del torneo', null=True),
        ),
        migrations.CreateModel(
            name='TournamentRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.PositiveIntegerField(default=0, help_text='Numero di vittorie')),
                ('draw', models.PositiveIntegerField(default=0, help_text='Numero di pareggi')),
                ('loss', models.PositiveIntegerField(default=0, help_text='Numero di sconfitte')),
                ('win_penalty', models.PositiveIntegerField(default=0, help_text='Numero di vittorie ai rigori')),
                ('loss_penalty', models.PositiveIntegerField(default=0, help_text='Numero di sconfitte ai rigori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tournament_rankings', to='core.seasonteam')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rankings', to='core.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
