# Generated by Django 5.2.3 on 2025-07-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tournament_end_date_tournament_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rosterslot',
            unique_together={('team', 'player'), ('team', 'shirt_number')},
        ),
    ]
