# Generated by Django 5.2.3 on 2025-07-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_rosterslot_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="fanta_value",
            field=models.PositiveIntegerField(
                default=50000, help_text="Valore di fanta-mercato del giocatore"
            ),
        ),
    ]
