# Generated by Django 5.2.3 on 2025-07-10 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_player_fanta_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('name', models.CharField(help_text='Nome del continente', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Codice ISO del continente', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nationality',
            name='continent',
            field=models.ForeignKey(blank=True, help_text='Continente di appartenenza', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to='core.continent'),
        ),
    ]
