version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - .venv:/workspace/.venv
    ports:
      - "8000:8000"
    command: >
      bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: node:20-bullseye
    working_dir: /app
    volumes:
      - ./frontend:/app   # supponendo che il frontend React stia in ./frontend
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start
