name: Python Lint and Test

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Run flake8 (lint)
      run: |
        flake8 .

    - name: Run tests with pytest
      run: |
        pytest core/tests.py -o log_cli_level=INFO


