# name: React CI

# on: [push, pull_request]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18

#     - name: Install dependencies
#       run: npm install

#     - name: Run lint
#       run: npm run lint
#       # Assicurati di avere uno script "lint" nel package.json, tipo "eslint src"

#     - name: Run tests
#       run: npm test
#       # Assicurati di avere script "test" configurato nel package.json

#     - name: Build project
#       run: npm run build
