name: React CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-
          node-

    - name: Install dependencies
      run: npm install

    - name: Check code format
      run: npm run format

    - name: TypeScript type check
      run: npm run typecheck

    - name: Run lint
      run: npm run lint

    - name: Create test results folder
      run: mkdir -p test-results

    - name: Run tests
      run: npm test

    - name: List coverage folder
      run: ls -la coverage

    - name: List test-results folder
      run: ls -la test-results

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: frontend/coverage

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: frontend/test-results/results.xml

    - name: Build project
      run: npm run build
